# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdevbox', '0002_auto_20160413_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='developers_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('highest_education', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('begin_education', models.DateField()),
                ('end_education', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='developers_employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('speciality', models.CharField(max_length=100)),
                ('previous_employer', models.CharField(max_length=100)),
                ('role_previous_employment', models.CharField(max_length=100)),
                ('begin_previous_employment', models.DateField()),
                ('end_previous_employment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='developers_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('portfoli_name', models.CharField(max_length=100)),
                ('portfoli_tech', models.CharField(max_length=100)),
                ('portfoli_link', models.CharField(max_length=100)),
                ('portfoli_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='developers',
            name='user',
        ),
        migrations.DeleteModel(
            name='developers',
        ),
    ]
